SubnauticaModding/QModManager

QModManager/Patcher.cs

Changes in this commit:
- Add an `-1` index check to see if the element exists in the list or not.

Fix exception caused while sorting mods that are not for the installed game.

---

QModManager/Utility/MainMenuMessages.cs

Handles dynamic assembly loading for `TextMeshProUGUI` and `Unity.UI.Text` in `MainMenuMessages`

Dynamic Text Assembly for MainMenuMessages

---

QModManager/Patching/ManifestValidator.cs

- Ensuring that entries from VersionDependencies end up in RequiredDependencies
- Necessary for proper sorting in SortedCollection

Sorting bug fix for VersionDependencies

---

QModManager/Patching/ManifestValidator.cs
QModManager/Patching/QModFactory.cs

- Applies the necessary recursive checks to the `ValidateDependencies` method
- Adds additional logging to `CheckRequiredMods` to list out all required mods

Proper recursive dependency checks

---

QModPluginEmulator/QModManager.QModPluginGenerator.csproj
QModPluginEmulator/QModPluginGenerator.cs

QModPluginGenerator now checks the timestamps for the QMM assemblies against a record, and if any don't match, clears the BepInEx cache. Uses Newtonsoft's BSON read/writer for storing assembly timestamps.
Addresses an issue where BepInEx type caches are not being correctly re-validated or cleared after an update to QMM, which in some cases leads to issues.

Clear BepInEx Cache on QMM Assembly Update

---

QModManager/Patching/ManifestValidator.cs

Updated the logging of RequiredMods with Debug Logs enabled so as not to throw errors. 
Yes @PrimeSonic, I know it uses LINQ, but it also means its less code-reproduction, and its only on load, and only if Debug Logs are enabled... Take the performance cost ;)

Fix logging required mods

---

QMMHarmonyShimmer/QMMHarmonyShimmer.cs

- Spefically catching the `BadImageFormatException` thrown when we attempt to shim an assembly that is not a valid format (ie. unmanaged) and improved logging for this.
- Also added log warnings when any version of `0Harmony.dll` is detected in a QMod subfolder to allow users, modders and support-staff alike to know that this will very likely cause issues and the mod should be updated or removed.
Closes #176

QMMHarmonyShimmer: Improved logging for invalid assemblies

---

QMMHarmonyShimmer/QMMHarmonyShimmer.cs
QModPluginEmulator/QModPluginGenerator.cs

Attempting to catch obscure errors in preloader patches to prevent our preloader patches from cancelling QMM load.

Aggressively add try{}catch blocks to our preloader patchers

---

QModManager/Patching/Patcher.cs
QModManager/Utility/IOUtilities.cs

- Splits the file tree logging into a separate log entry per line
- Uses `Console.Write` directly instead of `Logger` as we do not need to prepend all lines with meta-data
- Solves the issue of sending in one massive log that is too big for the log buffer

Split file tree logs

---

QModManager/Patching/ManifestValidator.cs
QModManager/Patching/ModStatus.cs
QModManager/Utility/SummaryLogger.cs

Added new `ModStatus`: `ModStatus.Obsolete` for mods so outdated they are no longer supported and will be skipped during the mod loading process.
Added 2 mods to the `ProhibitedModIDs` dictionary in `ManifestValidator.cs` with this new `Obsolete` status:
- AssetTools (`AgonyAssetTools`): Known to be breaking mod options menus for many, many mods. Every mod that every used it is basically dead and/or replaced by another mod.
- QMultiMod (`qmultimod.mod`): Supplanted by several other mods, basically never used, causing compatibility issues with mods that have replaced it.
Added appropriate logging when mods with the `Obsolete` status are skipped.

Ignore obsolete mods

---

QMMLoader/QMMLoader.cs

This change now makes QMM work when launching from the EXE as well as from the launcher.
Changes the Harmony Patch location in QMMLoader from GameInput.Awake to PlatformUtils.PlatformInitAsyc which causes QMM to not start making its changes until after the game has been restarted if it needs to be.

Launch From Exe

---

QModManager/Checks/PirateCheck.cs
QModManager/Patching/GameDetector.cs
QModManager/Utility/IOUtilities.cs

1. Updated the list of Piracy indicating Files.
2. Update the Timestamp to show the current clocktime to make it easier to indicate multiple Logfilke of the same person when providing help.
3. BZ introduce Steam Cloud Sync. I don't think we need that files to show up in the logfile.

3 Updates (Pirate,TimestampUpdate,SteamCloud)

---

QModPluginEmulator/QModPluginGenerator.cs

Identified a bug with the patch to `MirrorInternalLogs`:
When a log coming from a `BepInEx.Logging.ManualLogSource` comes in directly after one of the mid string trims applied in the patch (e.g. "(Filename: xdgodkdgx)", the patch unfortunately appears to trim both the intended line + the line coming from the `ManualLogSource`, and leaves an empty line behind.
Evidence of this occurring is in the [Fast Loading Screen](https://www.nexusmods.com/subnautica/mods/763) mod. The current release version of QMM for SN.STABLE leaves behind a large amount of empty lines after loading into the game, and Fast Loading Screen's logs are absent.
With the modifications I have made to this patch - which use a `Regex` to strip out occurrences of the intended string - results in the intended behaviour: the …

Applying a Regex to trim out the dirty string patterns instead

---

Dependencies/BZ.EXP/BepInEx.cfg
Dependencies/BZ.STABLE/BepInEx.cfg
Dependencies/SN.EXP/BepInEx.cfg
Dependencies/SN.STABLE/BepInEx.cfg
Installer/BZ.EXP.iss
Installer/BZ.STABLE.iss
Installer/SN.EXP.iss
Installer/SN.STABLE.iss
QModManager/BepInex/Plugins/QMMLoader.cs
QModManager/QMMLoader.cs
QModManager/QModManager.csproj
QModPluginEmulator/QModManager.QModPluginGenerator.csproj
QModPluginEmulator/QModPluginGenerator.cs

This PR aims to resolve the issue where BepInEx plugins are being destroyed on game launch - it addresses this by distributing a default BepInEx.cfg file that sets the entrypoint for BepInEx plugins to an appropriate starting point, i.e. after the wipe.
Additionally, since the initialization of QMods was moved from QMMLoader into QModPluginGenerator to workaround this issue, I have moved the initialization of QMods back into QMMLoader.
[QModManager_BZ.EXP.zip](https://github.com/SubnauticaModding/QModManager/files/6581176/QModManager_BZ.EXP.zip)
[QModManager_BZ.STABLE.zip](https://github.com/SubnauticaModding/QModManager/files/6581177/QModManager_BZ.STABLE.zip)
[QModManager_SN.EXP.zip](https://github.com/SubnauticaModding/QModManager/files/6581178/QModManager_SN.EXP.zip) …

Resolve BepInEx plugins being destroyed

---

QModManager/Patching/ManifestValidator.cs
QModManager/Patching/ModStatus.cs
QModManager/Patching/QModFactory.cs
QModManager/Utility/SummaryLogger.cs

- Better error logs when the mod.json file contains invalid JSON
- Adds a new ModStatus `ManifestParsingError`
- Renamed the ModStatus `MissingCoreInfo` to `MissingManifest` for clarity
- Updated relevant logs

Error logs for invalid JSON in mod.json

---

QModManager/Patching/Patcher.cs
QModPluginEmulator/QModPluginGenerator.cs
UnityAudioFixer/UnityAudioFixer.cs

Allows Bepinex folder and Qmods folder to be installed in locations other then the game dir so that you can just point the doorstop config to the install path and load mods from anywhere.
Mostly this is needed for possible upcoming mod managers to have mods loaded from different profiles and a few other possibilities.

Dynamic folder paths.

---

QModManager/Checks/NitroxCheck.cs
QModManager/Patching/Initializer.cs
QModManager/Patching/ManifestValidator.cs
QModManager/Utility/SummaryLogger.cs

Fixes an issue with Nitrox compatibility where mods that are marked as Nitrox compatible will be loaded even if they depend on mods which are _not_ Nitrox compatible, leading to glitchy behaviour.

Fix Nitrox dependency errors

---

QModManager/BepInex/Plugins/QMMLoader.cs
QModManager/HarmonyPatches/EnableConsoleSetting.cs
QModManager/OptionsManager.cs
QModManager/Patching/GameDetector.cs
QModManager/Utility/MainMenuMessages.cs
QModPluginEmulator/QModPluginGenerator.cs

remove audio fixer from check as it is now its own plugin and this check always fails on thunderstore install
PDA.time now exists on SN1.EXP allowing unification of time check. 
match other #if statements in repo 
Rewrite SpriteManager initialize check to not need preprocessor

Unify sn1.exp/bz installs

---

QModManager/API/IQModServices.cs
QModManager/API/QModServices.cs
QModManager/BepInex/Plugins/QMMLoader.cs
QModManager/Checks/PirateCheck.cs
QModManager/Patching/GameDetector.cs
QModManager/Patching/Patcher.cs
QModManager/Patching/StoreDetector.cs
QModManager/QModManager.csproj
QModManager/Utility/Dialog.cs

Adding a Store Detection for adding it into Logging.
Called before Fatal Error Exceptions to better indicate used Store without seeing Folder structur.
in addition could be indirect used as second Pirate check.
Warning was not able to test it myself properly.

Adding Store Detection for Logging

---

README.md

Just providing some more information on the readme. Hope I didn't get anything wrong :)

Add more beginner info to the README

---

QModManager/HarmonyPatches/MaskTelemetryLogging.cs
QModManager/Patching/GameDetector.cs
QModManager/QModManager.csproj

In the New BZ Update Personal Data in form of UserID of Steam/EPIC etc is gonna logged to the Log.
Top prevent leaks this info is masked just for Logging.

Masking Userdata in Logfile + Update BZ Version Number of Game

---

QModManager/BepInex/Plugins/LogFilter.cs
QModManager/BepInex/Plugins/QMMLoader.cs

Had at least one user in discord have their BZ process name as "Subnautica Below Zero" which prevented the mods from loading. I'm not sure if this is common or a them specific issue but figured it was easy enough to support

Fixed BepInProcess for atleast one Mac BZ user
